language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk

os:
  - linux

install:
  # Move cache directory if it exists
  - if [[ -d "${SMALLTALK_CI_CACHE}" ]]; then mv $SMALLTALK_CI_CACHE "$(pwd)"; fi
  # Make sure to use smalltalkCI from this branch
  - if [[ -n "${SMALLTALK_CI_HOME}" ]]; then rm -rf $SMALLTALK_CI_HOME && ln -s "$(pwd)" $SMALLTALK_CI_HOME; fi

matrix:
  include:
    # Bash tests
    - language: bash
      smalltalk:
      sudo: false
      script: bash tests/all_tests.sh

cache:
  directories:
    - $SMALLTALK_CI_CACHE